### ISSUE TITLE
Fix switches on Webkit browsers

### ISSUE THREAD

**Issue by nt1m** [nt1m/material-framework#1]

**Comment by PalmerAL** [comment]
Most things in this don't work in webkit browsers actually. some more examples:
![screen shot 2015-01-20 at 7 13 15 pm](https://cloud.githubusercontent.com/assets/10314059/5829491/9336a93c-a0d8-11e4-8a7d-a8c98ad96732.png)
![screen shot 2015-01-20 at 7 13 18 pm](https://cloud.githubusercontent.com/assets/10314059/5829492/9338acb4-a0d8-11e4-9435-7b480c19fc9c.png)
![screen shot 2015-01-20 at 7 13 30 pm](https://cloud.githubusercontent.com/assets/10314059/5829494/933aceae-a0d8-11e4-954d-e2a0031f550f.png)
![screen shot 2015-01-20 at 7 13 35 pm](https://cloud.githubusercontent.com/assets/10314059/5829493/933906be-a0d8-11e4-8e39-aa634d579c30.png)

Screenshots are from safari 7.1.

**Comment by PalmerAL** [comment]
It looks like most of this is just not having <code> -webkit</code>  prefixes for the transforms. I'll try to work on this soon.
