### ISSUE TITLE
Document colors

### ISSUE THREAD

**Issue by nt1m** [nt1m/material-framework#103]
We have a lot of available colors in the framework, but we don't document them. We should do so.

**Comment by kCenk** [comment]
What you could add extra to these colors is font colors as described in http://www.google.com/design/spec/style/color.html#color-ui-color-application
Alpha:
.87 - Text
.54 - Secondary Text
.26 - Disabled / Hint Text
.12 - Dividers

Cheers

**Comment by nt1m** [comment]
@kCenk Adding these colors shouldn't be hard, but I don't have much time to do so, feel free to submit a PR though. Also, body text is already used as text color on body. And secondary text has it's own text color class as well. But I agree it's nice to get color classes.
