### ISSUE TITLE
icon-share no longer works

### ISSUE THREAD

**Issue by nt1m** [nt1m/material-framework#122]
@PalmerAL I think it's a regression of #121

**Comment by PalmerAL** [comment]
I'm thinking that it might be good to go back to the previous icon font and undo #121. In addition, this made all of the icon codes wrong. I'm thinking this is a bug in fontello - the icon codes appear right, but once you add some icons and export the font, all the codes are changed, messing up the font.

**Comment by kelescenk** [comment]
What about using these icons? http://google.github.io/material-design-icons/

**Comment by PalmerAL** [comment]
@kCenk Those icons are just a set of svg's, not an icon font. They are working on this, though (google/material-design-icons#1), so hopefully this can be used soon.

**Comment by nt1m** [comment]
@kCenk Yes, this is an icon-font, the choice of icon-fonts is because this format is lighter than including all SVG in separate file. What can be done though is creatling an SVG symlink, but those are only supported by Firefox, and it would take as much time (or more) as updating this icon-font to include all icons.

**Comment by nt1m** [comment]
Ember-paper ships a pretty rich icon-font : https://github.com/miguelcobain/ember-paper/tree/master/vendor/material-icons

Maybe we can test that out. I also experimented with bootstrap-md's icon font but the quality was terrible.

**Comment by PalmerAL** [comment]
At this point, it looks like the official google font is coming pretty soon, and its probably better to just wait for that. The ember-paper icons are pretty good, though.

**Comment by kCenk** [comment]
@nt1m Yeah i remember reading that up that there is a font on the way from them :+1:  But there is a way to use the Material Design Icons with https://icomoon.io :)
