### ISSUE TITLE
missing icon

### ISSUE THREAD

**Issue by PalmerAL** [nt1m/material-framework#126]
The new icons look great, but icon-trash is missing. Is it possible to add this back?

**Comment by PalmerAL** [comment]
Also, icon-write needs to be renamed to icon-create in the demo

**Comment by nt1m** [comment]
@PalmerAL Will fix those. Didn't realize icon-trash got away though.

**Comment by nt1m** [comment]
Actually icon-trash is not gone, it's now icon-delete.
