### ISSUE TITLE
Improve charts dialog UI

### ISSUE THREAD

**Issue by nt1m** [nt1m/material-framework#167]
It kinda looks unfinished to me. I might be able to provide a mockup
- [ ] If radio buttons don't fit in the dialog, the last radio label falls into the next line
- [ ] Unnecessary scrollbars appear
- [ ] "Plus" button kinda looks strange
- [ ] Text cursor shows at a wrong position if no text is entered
- [ ] Editor tooltip can popup by focusing the table

**Comment by PalmerAL** [comment]
I believe this should be filed in scratchpad repository?

**Comment by PalmerAL** [comment]
the text cursor is a known firefox bug when using flexbox - not sure that is really fixable.

**Comment by nt1m** [comment]
@PalmerAL Just did it again :/ Too tired today
