### ISSUE TITLE
Update obsolete rules

### ISSUE THREAD

**Issue by nt1m** [nt1m/material-framework#190]
At: https://github.com/nt1m/material-framework/blob/gh-pages/css/material.css#L146

**Comment by moeenio** [comment]
What's obsolete here ?

**Comment by nt1m** [comment]
To be honest, I can't remember, I think maybe it was the half-opacity color that was too low for h2/h3. I guess I'll close this this for now.

**Comment by moeenio** [comment]
Taht's why you should use the issue desc lol
