### ISSUE TITLE
Improve demo page

### ISSUE THREAD

**Issue by nt1m** [nt1m/material-framework#51]
Things to do : 
- [x] Replace the heavy bunch of cards with lighter sections separated by a divider
- [ ] Add code samples
- [ ] Split into multiple pages ?

**Comment by PalmerAL** [comment]
I really like the replacement for the cards on the demo page. Some of the components (toolbars, cards) probably need som margin on the sides. Eventually, this should be split into multiple pages, but I'm not sure there is enough content right now for this. Probably after #21 is complete.

**Comment by nt1m** [comment]
@PalmerAL Fixed the margin. I agree this should be split up into multiple pages, I need to start some javascript components for this, and I probably don't have the time.

**Comment by PalmerAL** [comment]
Just wondering, what would you need javascript components for? For multiple pages, you could just use the tabs component.

**Comment by nt1m** [comment]
@PalmerAL I was thinking of doing this using a sidemenu, but tabs would probably work as well. I'd need to separate things in bigger categories though (I can't put too much tabs).
But anyways, it'd be nice to complete the framework with a few JS components, such as dropdown menus, or sidemenus, to make the framework a bit more useful.

**Comment by PalmerAL** [comment]
Right. Eventually, JS would be nice, but for right now it would be good to finish the css components first. Not every component would get its own tab, maybe something like:
-forms/input
-layout + cards
-buttons + icons
- typography
-contributing

**Comment by nt1m** [comment]
Sounds good ! Here's how I would go (pratically the same) : 
- Introduction (Contributing, download, ...)
- Forms (Inputs, buttons)
- Layout (cards, ...)
- Typography & Iconography

**Comment by PalmerAL** [comment]
Buttons aren't really a form item though - there are a lot of uses for them outside of forms, and they are used in a lot of other places (call to actions, dialogs, etc.)
