### ISSUE TITLE
typography section bug

### ISSUE THREAD

**Issue by PalmerAL** [nt1m/material-framework#65]
Having the fab button in the navbar affects the width of the typography section (although it does not do this for any other section - not sure why). 
![screen shot 2015-01-22 at 4 44 36 pm](https://cloud.githubusercontent.com/assets/10314059/5866369/31d05d12-a256-11e4-9d30-544ea9daf744.png)

**Comment by nt1m** [comment]
So the solution here would be to use absolute/fixed positioning

**Comment by PalmerAL** [comment]
Apparently, having a fixed position element inside of a sticky positioned element causes really weird behavior in webkit on ios. As you scroll down the page, the fab moves down the screen with the scroll until you stop scrolling. When you lift your finger up and start scrolling again, it moves back to the top, but then starts moving down the page again. Maybe move the fab outside of the toolbar?

**Comment by nt1m** [comment]
@PalmerAL I think that's a problem with fixed positioning. Maybe sticky positioning will work right ?

**Comment by PalmerAL** [comment]
Since the button is inside a navbar that sticks to the top of the screen anyway, I just changed the button to absolute positioning, which works fine.
